name: Build-Ubuntu-Clang

on:
  push:
    branches: ["*"]

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      BUILD64: ${{ github.workspace }}/build64
      BUILD32: ${{ github.workspace }}/build32

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Configure CMake 64
      run: >
        cmake -B ${{ env.BUILD64 }}
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
        -DTARGET_ARCH=64

    - name: Build 64
      run: cmake --build ${{ env.BUILD64 }} --config Release

    - name: Configure CMake 32
      run: >
        cmake -B ${{ env.BUILD32 }}
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
        -DTARGET_ARCH=32

    - name: Build 32
      run: cmake --build ${{ env.BUILD32 }} --config Release

    - name: Upload Build Results
      uses: actions/upload-artifact@v3
      with:
        name: binaries-ubuntu-clang-${{ github.sha }}
        path: |
          ${{ github.workspace }}/lua4/luac_64
          ${{ github.workspace }}/lua4/luac_32
          ${{ github.workspace }}/luadec_64
          ${{ github.workspace }}/luadec_32

