name: Build-Windows-MSVC

on:
  push:
    branches: ["*"]

jobs:
  main:
    runs-on: windows-latest

    env:
      BUILD64: ${{ github.workspace }}/build64
      BUILD32: ${{ github.workspace }}/build32

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Configure CMake x64
      run: >
        cmake -B ${{ env.BUILD64 }}
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
        -DTARGET_ARCH=64

    - name: Build x64
      run: cmake --build ${{ env.BUILD64 }} --config Release

    - name: Configure CMake x32
      run: >
        cmake -B ${{ env.BUILD32 }}
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
        -DTARGET_ARCH=32

    - name: Build x32
      run: cmake --build ${{ env.BUILD32 }} --config Release

    - name: Upload Build Results
      uses: actions/upload-artifact@v3
      with:
        name: binaries-windows-msvc-${{ github.sha }}
        path: |
          ${{ github.workspace }}/lua4/luac_x64.exe
          ${{ github.workspace }}/luadec_x64.exe
          ${{ github.workspace }}/luadec_x32.exe

