name: Test

on:
  push:
    branches: ["*"]

jobs:
  main:
    runs-on: windows-latest

    env:
      BUILD: ${{ github.workspace }}/build

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Configure CMake
      run: >
        cmake -B ${{ env.BUILD }}
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
        -DTARGET_ARCH=64

    - name: Build
      run: cmake --build ${{ env.BUILD }} --config Release

    - name: Test
      run: |
        '& test.exe lua4\\luac_64.exe luadec_64.exe differ.exe tests\\scripts\\'
