name: test

on:
  workflow_run:
    workflows [ "build" ]
    branches: [ "master" ]
    types: 
      - completed

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Test
      run: test lua4/luac lua4dec test/scripts/
