name: test

on:
  workflow_run:
    workflows: [ "build" ]
    branches: [ "master" ]
    types: 
      - completed

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            test: ./test
            compiler: ./lua4/luac
            decompiler: ./lua4dec
            scripts: ./tests/scripts/
          - os: windows-latest
            test: test.exe
            compiler: .\lua4\luac.exe
            decompiler: lua4dec.exe
            scripts: .\tests\scripts\

    steps:
    - name: Download Build Results
      uses: actions/download-artifact@v3
      with:
        name: binaries-${{ matrix.os }}
        path: ${{ github.workspace }}

    - name: Test
      run: ${{ matrix.test }} ${{ matrix.compiler }} ${{ matrix.decompiler }} ${{ matrix.scripts }}
