name: test

on:
  workflow_run:
    workflows: [ "build" ]
    branches: [ "master" ]
    types: 
      - completed

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            test: test.exe
            compiler: .\lua4\luac.exe
            decompiler: lua4dec.exe
            scripts: .\tests\scripts\
          - os: ubuntu-latest
            test: ./test
            compiler: ./lua4/luac
            decompiler: ./lua4dec
            scripts: ./tests/scripts/

    steps:
    - name: Test
      uses: actions/cache@v3
      with:
        key: binaries-${{ matrix.os }}-${{ github.sha }}
      run: ${{ matrix.test }} ${{ matrix.compiler }} ${{ matrix.decompiler }} ${{ matrix.scripts }}
